main = ".open-next/worker.js"
name = "umami"
compatibility_date = "2025-06-09"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false
preview_urls = false

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "umami"

[vars]
RUNTIME = "workerd"

# Advanced users can enable hyperdrive to optimize database connection latency. For usage, please refer to https://developers.cloudflare.com/hyperdrive/get-started/.
# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = ""
